### ISSUE TITLE
Impossible to destroy container if consistency check is not valid

### ISSUE THREAD

**Issue by larenso** [subutai-io/subos#60] opened 2016-03-07 09:18 UTC
Impossible to destroy container if consistency check is not valid, log file is attached
1) tried to create container, but it somehow created no consistent containers
2) couldn't destroy them
[output.txt](https://github.com/subutai-io/subos/files/161028/output.txt)

**Comment by soffokl** [comment] 2016-03-09 04:22
@larenso This problem was fixed few days ago. Do you using latest build?
https://github.com/subutai-io/base/issues/155

**Comment by soffokl** [comment] 2016-03-10 11:11
Duplicate of subutai-io/base#155

**Closed by soffokl** 2016-03-10 11:11 UTC
Labels: bug, duplicate
